const mongoose = require("mongoose");

const stockAnalysisSchema = new mongoose.Schema({
  symbol: { type: String, required: true, unique: true }, // e.g., NICA
  date: { type: String, required: true }, // "2026-01-21"
  lastPrice: Number,
  change: Number, // Daily change %

  // --- 1. THE RAW DATA (For Pro Users/Charts) ---
  indicators: {
    rsi: Number,
    macd: {
      value: Number,
      signal: Number,
      histogram: Number,
    },
    ema50: Number,
    ema200: Number,
    volume: Number,
    averageVolume: Number, // To detect spikes
  },

  // --- 2. THE EXPLAINABLE SIGNALS (The "Why") ---
  // This is the list of reasons generated by the Analyzer
  signals: [
    {
      type: { type: String, enum: ["BULLISH", "BEARISH", "NEUTRAL"] },
      indicator: String, // e.g., "RSI"
      message: String, // e.g., "RSI is oversold (<30), indicating the stock is undervalued."
      score: Number, // +1, -1, or 0
    },
  ],

  // --- 3. THE VERDICT ---
  totalScore: Number, // Sum of all signal scores (e.g., +4)
  recommendation: {
    type: String,
    enum: ["STRONG BUY", "BUY", "HOLD", "SELL", "STRONG SELL"],
  },

  updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("StockAnalysis", stockAnalysisSchema);
